name: API - Cypress Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  cypress-api:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o repositório
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # 2. Instala Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instala dependências
      - name: Instalar dependências NPM
        run: npm install

      # 4. Run Cypress Tests (modo headless)
      - name: Executar testes Cypress
        run: npm run cy:run

      # 5. Merge dos relatórios JSON do Mochawesome
      - name: Unificar relatórios Mochawesome
        run: npm run cy:report

      # 6. Gerar HTML final do relatório
      - name: Gerar relatório HTML Mochawesome
        run: npm run cy:generate

      # 7. Upload do relatório como artefato
      - name: Enviar relatório como artefato
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report
          path: cypress/reports/
